ci:
  skip: [mypy]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
    - id: pylint
      args:
        - --rcfile=pylintrc
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        stages: [manual] # temporarilt disable Mypy due to missing type stubs
        files: src/
        args:
          - --config-file
          - mypy.ini
