openapi: 3.0.3

info:
  title: Airport Air Quality Prediction API
  version: '1.0'
  description: API for predicting air quality based on airport information

paths:
  /air-quality:
    post:
      summary: Predict Air Quality from Airport Information
      description: |
        Uploads airport information and predicts air quality based on the provided data.
        Initiates background processing for prediction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Airport'
      responses:
        '201':
          description: |
            An air quality prediction has successfully been created and returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostAirQualityResponse'
              example:
                air_quality: 2.12
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - ApiKeyAuth: []

components:
  schemas:
    Airport:
      type: object
      properties:
        altitude:
          type: number
          description: Altitude of the airport in feet
        runways:
          type: array
          description: A list of available runways at the specified airport
          items:
            type: object
            properties:
              length_in_ft:
                type: number
                description: Length of the runway in feet
              surface:
                type: string
                enum:
                  - asphalt
                  - unknown
                  - Concrete
                  - turf
                  - bituminous
                  - macadam
                  - gravel
                  - dirt
                  - paved
                  - grass
                  - laterite
                  - tarmac
                  - coral
                  - sealed
                  - sand
                  - unpaved
                  - water
                  - clay
                  - soil
                  - silt
                  - treated
                  - ice
                description: Surface material of the runway
            required:
              - length
            additionalProperties: false
        total_arrivals:
          type: number
          description: Total number of arriving flights in the next 24 hours.
        total_departures:
          type: number
          description: Total number of departing flights in the next 24 hours.
      required:
        - altitude
        - runways
        - total_arrivals
        - total_departures
      additionalProperties: false

    PostAirQualityResponse:
      type: object
      properties:
        air_quality:
          type: number
          description: Predicted air quality value in PM10
      required:
        - air_quality
      additionalProperties: false

    Error:
      type: object
      description: |
        General error response body
      properties:
        errors:
          description: |
            This field MUST contain an array with at least one error model.
          type: array
          items:
            $ref: '#/components/schemas/ErrorItem'
          minItems: 1
        status_code:
          description: |
            This field MAY contain the HTTP status code used for the response. Otherwise, it MUST be omitted.
          type: integer
      required:
        - errors
      additionalProperties: false

    ErrorItem:
      description: |
        An error message.
      type: object
      properties:
        code:
          description: |
            This field MUST contain a snake case string succinctly identifying the problem.
            This field SHOULD NOT indicate which field, parameter, or header caused the error.
          type: string
        message:
          description: |
            This field MUST contain a plainly-written, developer-oriented explanation of the solution to the problem in complete, well-formed sentences.
          type: string
      required:
        - code
        - message
      additionalProperties: false

  responses:
    PostAirQualityResponse:
      description: Response from the air quality model
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostAirQualityResponse'

    BadRequest:
      description: |
        The request body or parameters were incorrect
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: |
        The API key is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: |
        The specified user does not have permission to perform this action
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-key
