name: 'Continuous Integration'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: pull lfs files
        run: git lfs pull
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run MyPy
        run: |
          mypy --install-types --non-interactive --config-file mypy.ini ./src ./tests
      - name: Run Pylint
        run: |
          python -m pylint ./src ./tests ./research
      - name: Run iSort
        run: |
          pip install isort
          isort --line-length 120 --check ./src ./tests
      - name: Decode credentials
        run: |
          echo "${{ secrets.TOKEN }}" | base64 --decode > token.json
      - name: Train model
        run: |
          python -m src.model.train_model
      - name: Run API tests
        run: |
          python -W ignore -m unittest discover -s "$(pwd)/tests" -p 'test*'
      - name: Delete secrets
        run: |
          rm tokens.json
